services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    environment:
      OPENAI_API_BASE_URL: http://proxy:8081/v1
      OPENAI_API_KEY: sk-proxy
      ENABLE_PERSISTENT_CONFIG: "True"
      WEBUI_AUTH: "False"
    ports:
      - "${OPENWEBUI_PORT}:8080"
    volumes:
      - ./cache/openwebui:/app/backend/data:rw${SELINUX_SUFFIX:-}
    networks: [ragnet]
    depends_on:
      proxy:
        condition: service_healthy
