permissions:
  - '*'
sessions:
  session:
    useTLS: false
    redirect: false
jobs:
  execute_job:
    ssh:
      remoteHost: ${{ inputs.resource.ip }}
      remoteUser: mattshax
    steps:
      - name: Preparing Run Directory
        run: |
          cd ~/
          sudo rm -Rf ${{ inputs.rundir }}
          git clone https://github.com/parallelworks/activate-rag-vllm.git ${{ inputs.rundir }}
      - name: Start Docker
        run: |
          cd ${{ inputs.rundir }}
          
'on':
  execute:
    inputs:
      resource:
        type: compute-clusters
        label: Compute Cluster
        autoselect: true
        include-workspace: false
        tooltip: Resource to run the service
      rundir:
        label: Run Directory
        type: string
        default: ~/activate-rag-vllm
      type:
        label: Type
        type: dropdown
        options:
          - value: docker
            label: Docker
          - value: singularity
            label: Singularity
      hftoken:
        label: HF Token (gated models)
        optional: true
        type: password
